### ISSUE TITLE
Package 'php' has no installation candidate

### ISSUE THREAD

**Issue by taikhoandota382** [mskian/my-termux-setup#1]
I tried to install PHP in BlueStacks by Termux, but thrown the below error :

Command : pkg install php
Error : Package 'php' has no installation candidate

I ran apt-get update and apt-get upgrade already.
 I checked pkg list-all , and there wasn't PHP Package in the list. 
Can you help me figure out this issue?

**Comment by mskian** [comment]
attach the error screenshot please

**Comment by taikhoandota382** [comment]
> attach the error screenshot please

![h10NQ](https://user-images.githubusercontent.com/81956567/113689711-92e45400-9705-11eb-8298-2b8a3ca6a5af.png)

**Comment by jollran2005** [comment]
I have the same problem

**Comment by shooty07** [comment]
> > attach the error screenshot please
> 
> ![h10NQ](https://user-images.githubusercontent.com/81956567/113689711-92e45400-9705-11eb-8298-2b8a3ca6a5af.png)

same problem

**Comment by mskian** [comment]
Let me check from my side and Update it

**Comment by HellBoy944** [comment]
I have the same prob
![IMG-20210713-WA0046](https://user-images.githubusercontent.com/87373612/125455089-131946ac-3414-425a-931b-ca01c8296764.jpeg)

**Comment by amirundead28** [comment]
still nobody cant fix this error?

**Comment by shooty07** [comment]
If you are using termux in PC with bluestacks emulator problem arises.  Try
to uninstall and reinstall termux in bluestacks.

**Comment by shenkz** [comment]
tried this but still not resolving the issue

**Comment by shooty07** [comment]
If you are using termux in bluestacks it wont solve or work.  Try on
mobile.

**Comment by mskian** [comment]
download termux via Fdriod and Try

**Comment by mskian** [comment]
try myself 
you can download Termux via F-Droid and install 
it will work
